### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [shapkarin/music-search#1]
Hi @shapkarin .. I wanted to contribute to your project and I've designed a logo for your project. if you need anything change please let me know.
Best Regard. Mirza Zulfan
![music search](https://user-images.githubusercontent.com/36124339/48052113-a9ef8680-e1d9-11e8-9357-6180e574154b.png)

**Comment by shapkarin** [comment]
@mirzazulfan great! I think everything is fine!

**Comment by shapkarin** [comment]
@mirzazulfan be careful, default branch is jade, but online is with underscore template (gh-pages brach). 
I'll make gh-pages default.

**Comment by shapkarin** [comment]
@mirzazulfan I like the first. But I'm not sure about faicon - it's small, so we just need to check :-)
Feel free to contribute :octocat:

**Comment by mirzazulfan** [comment]
Thanks for your response @shapkarin .. i'll send you files and pr. :)

**Comment by mirzazulfan** [comment]
Hi @shapkarin .. I've created a pr, #3
here's your files [Gdrive](https://drive.google.com/drive/folders/1bZk09NlcGYiZ4ao4g4YYhHbJ23-mq9lr?ogsrc=32) :+1:
